// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package dbgen

import (
	"context"
)

const createBlockFromLetter = `-- name: CreateBlockFromLetter :execrows
INSERT INTO blocks (blocker_id, blocked_id)
SELECT $1,
       CASE WHEN sender_id = $1 THEN recipient_id ELSE sender_id END
FROM letters
WHERE letters.id = $2
  AND opened_at IS NOT NULL
  AND recipient_id IS NOT NULL
  AND $1 IN (sender_id, recipient_id)
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $1 AND deleted_at IS NULL)
  AND EXISTS (
      SELECT 1 FROM identities
      WHERE identities.id = CASE WHEN sender_id = $1 THEN recipient_id ELSE sender_id END
        AND deleted_at IS NULL
  )
ON CONFLICT DO NOTHING
`

type CreateBlockFromLetterParams struct {
	IdentityID int64
	LetterID   string
}

func (q *Queries) CreateBlockFromLetter(ctx context.Context, arg CreateBlockFromLetterParams) (int64, error) {
	result, err := q.db.Exec(ctx, createBlockFromLetter, arg.IdentityID, arg.LetterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlock = `-- name: GetBlock :one
SELECT blocker_id, blocked_id, created_at FROM blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type GetBlockParams struct {
	BlockerID int64
	BlockedID int64
}

func (q *Queries) GetBlock(ctx context.Context, arg GetBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, getBlock, arg.BlockerID, arg.BlockedID)
	var i Block
	err := row.Scan(&i.BlockerID, &i.BlockedID, &i.CreatedAt)
	return i, err
}
