// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignLetterClaim = `-- name: AssignLetterClaim :one
WITH claim_time AS (SELECT clock_timestamp() AS value)
UPDATE letters
SET recipient_id = $1,
    recipient_alias = $2,
    claimed_at = claim_time.value,
    claim_expires_at = claim_time.value + interval '24 hours'
FROM claim_time
WHERE letters.id = $3
  AND letters.recipient_id IS NULL
  AND letters.withdrawn_at IS NULL
  AND letters.expires_at > claim_time.value
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = letters.sender_id AND identities.deleted_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM reports WHERE reports.letter_id = letters.id)
  AND NOT EXISTS (
      SELECT 1 FROM blocks
      WHERE (blocker_id = $1 AND blocked_id = letters.sender_id)
         OR (blocker_id = letters.sender_id AND blocked_id = $1)
  )
RETURNING letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at
`

type AssignLetterClaimParams struct {
	RecipientID    pgtype.Int8
	RecipientAlias pgtype.Text
	ID             string
}

func (q *Queries) AssignLetterClaim(ctx context.Context, arg AssignLetterClaimParams) (Letter, error) {
	row := q.db.QueryRow(ctx, assignLetterClaim, arg.RecipientID, arg.RecipientAlias, arg.ID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const getActiveClaimForUpdate = `-- name: GetActiveClaimForUpdate :one
SELECT id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at FROM letters
WHERE recipient_id = $1
  AND opened_at IS NULL
  AND claim_expires_at > clock_timestamp()
  AND recipient_removed_at IS NULL
ORDER BY claimed_at, id
FOR UPDATE
`

func (q *Queries) GetActiveClaimForUpdate(ctx context.Context, recipientID pgtype.Int8) (Letter, error) {
	row := q.db.QueryRow(ctx, getActiveClaimForUpdate, recipientID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const releaseExpiredClaimsForIdentity = `-- name: ReleaseExpiredClaimsForIdentity :execrows
UPDATE letters
SET recipient_id = NULL,
    recipient_alias = NULL,
    claimed_at = NULL,
    claim_expires_at = NULL,
    recipient_removed_at = NULL
WHERE recipient_id = $1
  AND opened_at IS NULL
  AND claim_expires_at <= clock_timestamp()
`

func (q *Queries) ReleaseExpiredClaimsForIdentity(ctx context.Context, recipientID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExpiredClaimsForIdentity, recipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectEligibleLetterForClaim = `-- name: SelectEligibleLetterForClaim :one
SELECT id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at FROM letters
WHERE recipient_id IS NULL
  AND withdrawn_at IS NULL
  AND expires_at > clock_timestamp()
  AND sender_id <> $1
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = letters.sender_id AND identities.deleted_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM reports WHERE reports.letter_id = letters.id)
  AND NOT EXISTS (
      SELECT 1 FROM blocks
      WHERE (blocker_id = $1 AND blocked_id = letters.sender_id)
         OR (blocker_id = letters.sender_id AND blocked_id = $1)
  )
ORDER BY created_at, id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) SelectEligibleLetterForClaim(ctx context.Context, recipientID int64) (Letter, error) {
	row := q.db.QueryRow(ctx, selectEligibleLetterForClaim, recipientID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}
