// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package dbgen

import (
	"context"
)

const deleteExpiredAccessSessions = `-- name: DeleteExpiredAccessSessions :execrows
DELETE FROM access_sessions
WHERE expires_at <= now() OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredAccessSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAccessSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAccessSessionsBatch = `-- name: DeleteExpiredAccessSessionsBatch :many
WITH expired AS (
    SELECT token_hash FROM access_sessions
    WHERE expires_at <= now() OR revoked_at IS NOT NULL
    ORDER BY expires_at, token_hash
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM access_sessions
USING expired
WHERE access_sessions.token_hash = expired.token_hash
RETURNING access_sessions.token_hash
`

func (q *Queries) DeleteExpiredAccessSessionsBatch(ctx context.Context, batchSize int32) ([][]byte, error) {
	rows, err := q.db.Query(ctx, deleteExpiredAccessSessionsBatch, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var token_hash []byte
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredAuthChallenges = `-- name: DeleteExpiredAuthChallenges :execrows
DELETE FROM auth_challenges
WHERE expires_at <= now() OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredAuthChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthChallengesBatch = `-- name: DeleteExpiredAuthChallengesBatch :many
WITH expired AS (
    SELECT id FROM auth_challenges
    WHERE expires_at <= now() OR used_at IS NOT NULL
    ORDER BY expires_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM auth_challenges
USING expired
WHERE auth_challenges.id = expired.id
RETURNING auth_challenges.id
`

func (q *Queries) DeleteExpiredAuthChallengesBatch(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredAuthChallengesBatch, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredDPoPReplays = `-- name: DeleteExpiredDPoPReplays :execrows
DELETE FROM dpop_replays
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredDPoPReplays(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDPoPReplays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDPoPReplaysBatch = `-- name: DeleteExpiredDPoPReplaysBatch :many
WITH expired AS (
    SELECT session_token_hash, jti_hash FROM dpop_replays
    WHERE expires_at <= now()
    ORDER BY expires_at, session_token_hash, jti_hash
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM dpop_replays
USING expired
WHERE dpop_replays.session_token_hash = expired.session_token_hash
  AND dpop_replays.jti_hash = expired.jti_hash
RETURNING dpop_replays.jti_hash
`

func (q *Queries) DeleteExpiredDPoPReplaysBatch(ctx context.Context, batchSize int32) ([][]byte, error) {
	rows, err := q.db.Query(ctx, deleteExpiredDPoPReplaysBatch, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var jti_hash []byte
		if err := rows.Scan(&jti_hash); err != nil {
			return nil, err
		}
		items = append(items, jti_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredModerationAudit = `-- name: DeleteExpiredModerationAudit :many
WITH expired AS (
    SELECT id FROM moderation_audit
    WHERE purge_at <= now()
    ORDER BY purge_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM moderation_audit
USING expired
WHERE moderation_audit.id = expired.id
RETURNING moderation_audit.id
`

func (q *Queries) DeleteExpiredModerationAudit(ctx context.Context, batchSize int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteExpiredModerationAudit, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredReports = `-- name: DeleteExpiredReports :many
WITH expired AS (
    SELECT id FROM reports
    WHERE record_purge_at <= now()
    ORDER BY record_purge_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM reports
USING expired
WHERE reports.id = expired.id
RETURNING reports.id
`

func (q *Queries) DeleteExpiredReports(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredReports, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredWaitingLetters = `-- name: DeleteExpiredWaitingLetters :many
WITH expired AS (
    SELECT id FROM letters
    WHERE recipient_id IS NULL
      AND withdrawn_at IS NULL
      AND expires_at <= now()
    ORDER BY expires_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM letters
USING expired
WHERE letters.id = expired.id
RETURNING letters.id
`

func (q *Queries) DeleteExpiredWaitingLetters(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredWaitingLetters, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredWithdrawnLetters = `-- name: DeleteExpiredWithdrawnLetters :many
WITH expired AS (
    SELECT id FROM letters
    WHERE recipient_id IS NULL
      AND withdrawn_at IS NOT NULL
      AND expires_at <= now()
    ORDER BY expires_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM letters
USING expired
WHERE letters.id = expired.id
RETURNING letters.id
`

func (q *Queries) DeleteExpiredWithdrawnLetters(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredWithdrawnLetters, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNextReportForEvidencePurge = `-- name: LockNextReportForEvidencePurge :one
SELECT id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at FROM reports
WHERE evidence_purge_at IS NOT NULL
  AND evidence_purge_at <= now()
  AND evidence_purged_at IS NULL
ORDER BY evidence_purge_at, id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) LockNextReportForEvidencePurge(ctx context.Context) (Report, error) {
	row := q.db.QueryRow(ctx, lockNextReportForEvidencePurge)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const purgeReportEvidence = `-- name: PurgeReportEvidence :one
UPDATE reports
SET evidence_ciphertext = NULL,
    evidence_nonce = NULL,
    evidence_wrapped_key = NULL,
    evidence_kms_key_id = NULL,
    evidence_encryption_version = NULL,
    evidence_purged_at = now()
WHERE id = $1
  AND evidence_purge_at <= now()
  AND evidence_purged_at IS NULL
RETURNING id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at
`

func (q *Queries) PurgeReportEvidence(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, purgeReportEvidence, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const releaseExpiredClaims = `-- name: ReleaseExpiredClaims :many
WITH expired AS (
    SELECT id FROM letters
    WHERE opened_at IS NULL AND claim_expires_at <= now()
    ORDER BY claim_expires_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
), deleted AS (
    DELETE FROM letters
    USING expired
    WHERE letters.id = expired.id
      AND letters.sender_removed_at IS NOT NULL
    RETURNING letters.id
), released AS (
    UPDATE letters
    SET recipient_id = NULL,
        recipient_alias = NULL,
        claimed_at = NULL,
        claim_expires_at = NULL,
        recipient_removed_at = NULL
    FROM expired
    WHERE letters.id = expired.id
      AND letters.sender_removed_at IS NULL
    RETURNING letters.id
)
SELECT id FROM deleted
UNION ALL
SELECT id FROM released
`

func (q *Queries) ReleaseExpiredClaims(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, releaseExpiredClaims, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
