// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aliasKeyAvailable = `-- name: AliasKeyAvailable :one
SELECT NOT EXISTS (
    SELECT 1 FROM identities WHERE identities.alias_key = $1
    UNION ALL
    SELECT 1 FROM alias_reservations WHERE alias_reservations.alias_key = $1
) AS available
`

func (q *Queries) AliasKeyAvailable(ctx context.Context, aliasKey pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, aliasKeyAvailable, aliasKey)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const createIdentity = `-- name: CreateIdentity :one
WITH reservation AS (
    INSERT INTO alias_reservations (alias_key)
    VALUES ($5)
    ON CONFLICT DO NOTHING
    RETURNING alias_key
), creation AS (SELECT clock_timestamp() AS value)
INSERT INTO identities (public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at)
SELECT $1, $2, $3, $4,
       reservation.alias_key, creation.value, creation.value
FROM reservation CROSS JOIN creation
RETURNING id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at
`

type CreateIdentityParams struct {
	PublicKey      []byte
	KeyThumbprint  []byte
	RevocationHash []byte
	Alias          pgtype.Text
	AliasKey       string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.PublicKey,
		arg.KeyThumbprint,
		arg.RevocationHash,
		arg.Alias,
		arg.AliasKey,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
WITH creation AS (SELECT clock_timestamp() AS value)
INSERT INTO invites (token_hash, created_at, expires_at)
SELECT $1, creation.value, creation.value + interval '7 days'
FROM creation
RETURNING token_hash, created_at, expires_at, redeemed_at, redeemed_by, revoked_at
`

func (q *Queries) CreateInvite(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite, tokenHash)
	var i Invite
	err := row.Scan(
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.RevokedAt,
	)
	return i, err
}

const deleteFullyRemovedIdentityLetters = `-- name: DeleteFullyRemovedIdentityLetters :execrows
DELETE FROM letters
WHERE (sender_id = $1 OR recipient_id = $1)
  AND sender_removed_at IS NOT NULL
  AND (recipient_id IS NULL OR recipient_removed_at IS NOT NULL)
`

func (q *Queries) DeleteFullyRemovedIdentityLetters(ctx context.Context, identityID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFullyRemovedIdentityLetters, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdentityBlocks = `-- name: DeleteIdentityBlocks :execrows
DELETE FROM blocks
WHERE blocker_id = $1 OR blocked_id = $1
`

func (q *Queries) DeleteIdentityBlocks(ctx context.Context, identityID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentityBlocks, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdentityWaitingLetters = `-- name: DeleteIdentityWaitingLetters :execrows
DELETE FROM letters
WHERE sender_id = $1 AND recipient_id IS NULL
`

func (q *Queries) DeleteIdentityWaitingLetters(ctx context.Context, identityID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentityWaitingLetters, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveIdentityByPublicKey = `-- name: GetActiveIdentityByPublicKey :one
SELECT id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at FROM identities
WHERE public_key = $1 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

func (q *Queries) GetActiveIdentityByPublicKey(ctx context.Context, publicKey []byte) (Identity, error) {
	row := q.db.QueryRow(ctx, getActiveIdentityByPublicKey, publicKey)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveIdentityByThumbprint = `-- name: GetActiveIdentityByThumbprint :one
SELECT id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at FROM identities
WHERE key_thumbprint = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActiveIdentityByThumbprint(ctx context.Context, keyThumbprint []byte) (Identity, error) {
	row := q.db.QueryRow(ctx, getActiveIdentityByThumbprint, keyThumbprint)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at FROM identities WHERE id = $1
`

func (q *Queries) GetIdentityByID(ctx context.Context, id int64) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIdentityByRevocationHashForUpdate = `-- name: GetIdentityByRevocationHashForUpdate :one
SELECT id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at FROM identities
WHERE revocation_hash = $1 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

func (q *Queries) GetIdentityByRevocationHashForUpdate(ctx context.Context, revocationHash []byte) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByRevocationHashForUpdate, revocationHash)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInviteForUpdate = `-- name: GetInviteForUpdate :one
SELECT token_hash, created_at, expires_at, redeemed_at, redeemed_by, revoked_at FROM invites
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetInviteForUpdate(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteForUpdate, tokenHash)
	var i Invite
	err := row.Scan(
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.RevokedAt,
	)
	return i, err
}

const getRedeemableInviteForUpdate = `-- name: GetRedeemableInviteForUpdate :one
SELECT token_hash, created_at, expires_at, redeemed_at, redeemed_by, revoked_at FROM invites
WHERE token_hash = $1
  AND redeemed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > clock_timestamp()
FOR UPDATE
`

func (q *Queries) GetRedeemableInviteForUpdate(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getRedeemableInviteForUpdate, tokenHash)
	var i Invite
	err := row.Scan(
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.RevokedAt,
	)
	return i, err
}

const lockActiveIdentity = `-- name: LockActiveIdentity :one
SELECT id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at FROM identities
WHERE id = $1 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

func (q *Queries) LockActiveIdentity(ctx context.Context, id int64) (Identity, error) {
	row := q.db.QueryRow(ctx, lockActiveIdentity, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockIdentity = `-- name: LockIdentity :one
SELECT id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at FROM identities
WHERE id = $1
FOR NO KEY UPDATE
`

func (q *Queries) LockIdentity(ctx context.Context, id int64) (Identity, error) {
	row := q.db.QueryRow(ctx, lockIdentity, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockNextInactiveIdentity = `-- name: LockNextInactiveIdentity :one
SELECT id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at FROM identities
WHERE deleted_at IS NULL AND last_seen_at <= now() - interval '1 year'
ORDER BY last_seen_at, id
FOR NO KEY UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) LockNextInactiveIdentity(ctx context.Context) (Identity, error) {
	row := q.db.QueryRow(ctx, lockNextInactiveIdentity)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockRegistrationKey = `-- name: LockRegistrationKey :exec
SELECT pg_advisory_xact_lock(hashtextextended(encode($1::bytea, 'hex'), 0))
`

func (q *Queries) LockRegistrationKey(ctx context.Context, keyThumbprint []byte) error {
	_, err := q.db.Exec(ctx, lockRegistrationKey, keyThumbprint)
	return err
}

const markIdentityDeleted = `-- name: MarkIdentityDeleted :one
UPDATE identities
SET revocation_hash = NULL,
    alias = NULL,
    alias_key = NULL,
    deleted_at = clock_timestamp()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, public_key, key_thumbprint, revocation_hash, alias, alias_key, created_at, last_seen_at, deleted_at
`

func (q *Queries) MarkIdentityDeleted(ctx context.Context, id int64) (Identity, error) {
	row := q.db.QueryRow(ctx, markIdentityDeleted, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.RevocationHash,
		&i.Alias,
		&i.AliasKey,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const redeemInvite = `-- name: RedeemInvite :one
UPDATE invites
SET redeemed_at = clock_timestamp(), redeemed_by = $1
WHERE token_hash = $2
  AND redeemed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > clock_timestamp()
RETURNING token_hash, created_at, expires_at, redeemed_at, redeemed_by, revoked_at
`

type RedeemInviteParams struct {
	IdentityID pgtype.Int8
	TokenHash  []byte
}

func (q *Queries) RedeemInvite(ctx context.Context, arg RedeemInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, redeemInvite, arg.IdentityID, arg.TokenHash)
	var i Invite
	err := row.Scan(
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.RevokedAt,
	)
	return i, err
}

const releaseIdentityUnopenedClaims = `-- name: ReleaseIdentityUnopenedClaims :execrows
WITH deleted AS (
    DELETE FROM letters
    WHERE recipient_id = $1
      AND opened_at IS NULL
      AND sender_removed_at IS NOT NULL
)
UPDATE letters
SET recipient_id = NULL,
    recipient_alias = NULL,
    claimed_at = NULL,
    claim_expires_at = NULL,
    recipient_removed_at = NULL
WHERE letters.recipient_id = $1
  AND letters.opened_at IS NULL
  AND letters.sender_removed_at IS NULL
`

func (q *Queries) ReleaseIdentityUnopenedClaims(ctx context.Context, identityID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIdentityUnopenedClaims, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeIdentityKeepsakes = `-- name: RemoveIdentityKeepsakes :execrows
UPDATE letters
SET sender_removed_at = CASE WHEN sender_id = $1 THEN clock_timestamp() ELSE sender_removed_at END,
    recipient_removed_at = CASE WHEN recipient_id = $1 THEN clock_timestamp() ELSE recipient_removed_at END
WHERE (sender_id = $1 AND recipient_id IS NOT NULL)
   OR (recipient_id = $1 AND opened_at IS NOT NULL)
`

func (q *Queries) RemoveIdentityKeepsakes(ctx context.Context, identityID int64) (int64, error) {
	result, err := q.db.Exec(ctx, removeIdentityKeepsakes, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveIdentityAlias = `-- name: ReserveIdentityAlias :execrows
INSERT INTO alias_reservations (alias_key)
SELECT alias_key FROM identities
WHERE id = $1 AND alias_key IS NOT NULL
ON CONFLICT DO NOTHING
`

func (q *Queries) ReserveIdentityAlias(ctx context.Context, identityID int64) (int64, error) {
	result, err := q.db.Exec(ctx, reserveIdentityAlias, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invites
SET revoked_at = clock_timestamp()
WHERE token_hash = $1
  AND redeemed_at IS NULL
  AND revoked_at IS NULL
`

func (q *Queries) RevokeInvite(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchIdentity = `-- name: TouchIdentity :execrows
UPDATE identities
SET last_seen_at = clock_timestamp()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TouchIdentity(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, touchIdentity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
