// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keepsakes.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFullyRemovedLetter = `-- name: DeleteFullyRemovedLetter :execrows
DELETE FROM letters
WHERE letters.id = $1
  AND sender_removed_at IS NOT NULL
  AND (recipient_id IS NULL OR recipient_removed_at IS NOT NULL)
`

func (q *Queries) DeleteFullyRemovedLetter(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFullyRemovedLetter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReceivedKeepsakes = `-- name: ListReceivedKeepsakes :many
SELECT letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at FROM letters
WHERE letters.recipient_id = $1
  AND letters.opened_at IS NOT NULL
  AND letters.recipient_removed_at IS NULL
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $1 AND deleted_at IS NULL)
ORDER BY letters.created_at DESC, letters.id DESC
LIMIT $2
`

type ListReceivedKeepsakesParams struct {
	IdentityID pgtype.Int8
	PageSize   int32
}

func (q *Queries) ListReceivedKeepsakes(ctx context.Context, arg ListReceivedKeepsakesParams) ([]Letter, error) {
	rows, err := q.db.Query(ctx, listReceivedKeepsakes, arg.IdentityID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderAlias,
			&i.RecipientAlias,
			&i.BodyCiphertext,
			&i.BodyNonce,
			&i.BodyWrappedKey,
			&i.BodyKmsKeyID,
			&i.BodyEncryptionVersion,
			&i.FoldSeed,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimExpiresAt,
			&i.OpenedAt,
			&i.ReplyID,
			&i.ReplyCiphertext,
			&i.ReplyNonce,
			&i.ReplyWrappedKey,
			&i.ReplyKmsKeyID,
			&i.ReplyEncryptionVersion,
			&i.RepliedAt,
			&i.WithdrawnAt,
			&i.ExpiresAt,
			&i.SenderRemovedAt,
			&i.RecipientRemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedKeepsakesAfter = `-- name: ListReceivedKeepsakesAfter :many
SELECT letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at FROM letters
WHERE letters.recipient_id = $1
  AND letters.opened_at IS NOT NULL
  AND letters.recipient_removed_at IS NULL
  AND (letters.created_at, letters.id) < ($2, $3::varchar(22))
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $1 AND deleted_at IS NULL)
ORDER BY letters.created_at DESC, letters.id DESC
LIMIT $4
`

type ListReceivedKeepsakesAfterParams struct {
	IdentityID      pgtype.Int8
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	PageSize        int32
}

func (q *Queries) ListReceivedKeepsakesAfter(ctx context.Context, arg ListReceivedKeepsakesAfterParams) ([]Letter, error) {
	rows, err := q.db.Query(ctx, listReceivedKeepsakesAfter,
		arg.IdentityID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderAlias,
			&i.RecipientAlias,
			&i.BodyCiphertext,
			&i.BodyNonce,
			&i.BodyWrappedKey,
			&i.BodyKmsKeyID,
			&i.BodyEncryptionVersion,
			&i.FoldSeed,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimExpiresAt,
			&i.OpenedAt,
			&i.ReplyID,
			&i.ReplyCiphertext,
			&i.ReplyNonce,
			&i.ReplyWrappedKey,
			&i.ReplyKmsKeyID,
			&i.ReplyEncryptionVersion,
			&i.RepliedAt,
			&i.WithdrawnAt,
			&i.ExpiresAt,
			&i.SenderRemovedAt,
			&i.RecipientRemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentKeepsakes = `-- name: ListSentKeepsakes :many
SELECT letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at FROM letters
WHERE letters.sender_id = $1
  AND letters.sender_removed_at IS NULL
  AND (letters.recipient_id IS NOT NULL OR letters.expires_at > clock_timestamp())
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $1 AND deleted_at IS NULL)
ORDER BY letters.created_at DESC, letters.id DESC
LIMIT $2
`

type ListSentKeepsakesParams struct {
	IdentityID int64
	PageSize   int32
}

func (q *Queries) ListSentKeepsakes(ctx context.Context, arg ListSentKeepsakesParams) ([]Letter, error) {
	rows, err := q.db.Query(ctx, listSentKeepsakes, arg.IdentityID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderAlias,
			&i.RecipientAlias,
			&i.BodyCiphertext,
			&i.BodyNonce,
			&i.BodyWrappedKey,
			&i.BodyKmsKeyID,
			&i.BodyEncryptionVersion,
			&i.FoldSeed,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimExpiresAt,
			&i.OpenedAt,
			&i.ReplyID,
			&i.ReplyCiphertext,
			&i.ReplyNonce,
			&i.ReplyWrappedKey,
			&i.ReplyKmsKeyID,
			&i.ReplyEncryptionVersion,
			&i.RepliedAt,
			&i.WithdrawnAt,
			&i.ExpiresAt,
			&i.SenderRemovedAt,
			&i.RecipientRemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentKeepsakesAfter = `-- name: ListSentKeepsakesAfter :many
SELECT letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at FROM letters
WHERE letters.sender_id = $1
  AND letters.sender_removed_at IS NULL
  AND (letters.recipient_id IS NOT NULL OR letters.expires_at > clock_timestamp())
  AND (letters.created_at, letters.id) < ($2, $3::varchar(22))
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $1 AND deleted_at IS NULL)
ORDER BY letters.created_at DESC, letters.id DESC
LIMIT $4
`

type ListSentKeepsakesAfterParams struct {
	IdentityID      int64
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	PageSize        int32
}

func (q *Queries) ListSentKeepsakesAfter(ctx context.Context, arg ListSentKeepsakesAfterParams) ([]Letter, error) {
	rows, err := q.db.Query(ctx, listSentKeepsakesAfter,
		arg.IdentityID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderAlias,
			&i.RecipientAlias,
			&i.BodyCiphertext,
			&i.BodyNonce,
			&i.BodyWrappedKey,
			&i.BodyKmsKeyID,
			&i.BodyEncryptionVersion,
			&i.FoldSeed,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimExpiresAt,
			&i.OpenedAt,
			&i.ReplyID,
			&i.ReplyCiphertext,
			&i.ReplyNonce,
			&i.ReplyWrappedKey,
			&i.ReplyKmsKeyID,
			&i.ReplyEncryptionVersion,
			&i.RepliedAt,
			&i.WithdrawnAt,
			&i.ExpiresAt,
			&i.SenderRemovedAt,
			&i.RecipientRemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReceivedKeepsake = `-- name: RemoveReceivedKeepsake :one
UPDATE letters
SET recipient_removed_at = now()
WHERE letters.id = $1
  AND letters.recipient_id = $2
  AND letters.opened_at IS NOT NULL
  AND letters.recipient_removed_at IS NULL
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $2 AND deleted_at IS NULL)
RETURNING id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at
`

type RemoveReceivedKeepsakeParams struct {
	ID         string
	IdentityID pgtype.Int8
}

func (q *Queries) RemoveReceivedKeepsake(ctx context.Context, arg RemoveReceivedKeepsakeParams) (Letter, error) {
	row := q.db.QueryRow(ctx, removeReceivedKeepsake, arg.ID, arg.IdentityID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const removeSentKeepsake = `-- name: RemoveSentKeepsake :one
UPDATE letters
SET sender_removed_at = now()
WHERE letters.id = $1
  AND letters.sender_id = $2
  AND letters.sender_removed_at IS NULL
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $2 AND deleted_at IS NULL)
RETURNING id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at
`

type RemoveSentKeepsakeParams struct {
	ID         string
	IdentityID int64
}

func (q *Queries) RemoveSentKeepsake(ctx context.Context, arg RemoveSentKeepsakeParams) (Letter, error) {
	row := q.db.QueryRow(ctx, removeSentKeepsake, arg.ID, arg.IdentityID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}
