// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: letters.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLetterReply = `-- name: AddLetterReply :one
UPDATE letters
SET reply_id = $1,
    reply_ciphertext = $2,
    reply_nonce = $3,
    reply_wrapped_key = $4,
    reply_kms_key_id = $5,
    reply_encryption_version = $6,
    replied_at = now()
WHERE letters.id = $7
  AND letters.recipient_id = $8
  AND letters.opened_at IS NOT NULL
  AND letters.reply_id IS NULL
  AND letters.recipient_removed_at IS NULL
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $8 AND deleted_at IS NULL)
RETURNING id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at
`

type AddLetterReplyParams struct {
	ReplyID                pgtype.Text
	ReplyCiphertext        []byte
	ReplyNonce             []byte
	ReplyWrappedKey        []byte
	ReplyKmsKeyID          pgtype.Text
	ReplyEncryptionVersion pgtype.Int2
	ID                     string
	RecipientID            pgtype.Int8
}

func (q *Queries) AddLetterReply(ctx context.Context, arg AddLetterReplyParams) (Letter, error) {
	row := q.db.QueryRow(ctx, addLetterReply,
		arg.ReplyID,
		arg.ReplyCiphertext,
		arg.ReplyNonce,
		arg.ReplyWrappedKey,
		arg.ReplyKmsKeyID,
		arg.ReplyEncryptionVersion,
		arg.ID,
		arg.RecipientID,
	)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const createLetter = `-- name: CreateLetter :one
INSERT INTO letters (
    id, sender_id, sender_alias, body_ciphertext, body_nonce, body_wrapped_key,
    body_kms_key_id, body_encryption_version, fold_seed, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, now() + interval '7 days'
)
RETURNING id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at
`

type CreateLetterParams struct {
	ID                    string
	SenderID              int64
	SenderAlias           string
	BodyCiphertext        []byte
	BodyNonce             []byte
	BodyWrappedKey        []byte
	BodyKmsKeyID          string
	BodyEncryptionVersion int16
	FoldSeed              int64
}

func (q *Queries) CreateLetter(ctx context.Context, arg CreateLetterParams) (Letter, error) {
	row := q.db.QueryRow(ctx, createLetter,
		arg.ID,
		arg.SenderID,
		arg.SenderAlias,
		arg.BodyCiphertext,
		arg.BodyNonce,
		arg.BodyWrappedKey,
		arg.BodyKmsKeyID,
		arg.BodyEncryptionVersion,
		arg.FoldSeed,
	)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const expiredClaimExistsForRecipient = `-- name: ExpiredClaimExistsForRecipient :one
SELECT EXISTS (
    SELECT 1 FROM letters
    JOIN identities ON identities.id = $1 AND identities.deleted_at IS NULL
    WHERE letters.id = $2
      AND letters.recipient_id = $1
      AND letters.opened_at IS NULL
      AND letters.claim_expires_at <= now()
) AS expired
`

type ExpiredClaimExistsForRecipientParams struct {
	RecipientID int64
	ID          string
}

func (q *Queries) ExpiredClaimExistsForRecipient(ctx context.Context, arg ExpiredClaimExistsForRecipientParams) (bool, error) {
	row := q.db.QueryRow(ctx, expiredClaimExistsForRecipient, arg.RecipientID, arg.ID)
	var expired bool
	err := row.Scan(&expired)
	return expired, err
}

const getLetterByReplyIDForRecipient = `-- name: GetLetterByReplyIDForRecipient :one
SELECT id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at FROM letters
WHERE letters.recipient_id = $1
  AND letters.reply_id = $2
  AND letters.recipient_removed_at IS NULL
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $1 AND deleted_at IS NULL)
`

type GetLetterByReplyIDForRecipientParams struct {
	RecipientID pgtype.Int8
	ReplyID     pgtype.Text
}

func (q *Queries) GetLetterByReplyIDForRecipient(ctx context.Context, arg GetLetterByReplyIDForRecipientParams) (Letter, error) {
	row := q.db.QueryRow(ctx, getLetterByReplyIDForRecipient, arg.RecipientID, arg.ReplyID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const getLetterForOpen = `-- name: GetLetterForOpen :one
SELECT letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at FROM letters
JOIN identities ON identities.id = $1 AND identities.deleted_at IS NULL
WHERE letters.id = $2
  AND letters.recipient_id = $1
  AND letters.recipient_removed_at IS NULL
  AND (letters.opened_at IS NOT NULL OR letters.claim_expires_at > now())
`

type GetLetterForOpenParams struct {
	RecipientID int64
	ID          string
}

func (q *Queries) GetLetterForOpen(ctx context.Context, arg GetLetterForOpenParams) (Letter, error) {
	row := q.db.QueryRow(ctx, getLetterForOpen, arg.RecipientID, arg.ID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const getLetterForRecipient = `-- name: GetLetterForRecipient :one
SELECT letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at FROM letters
JOIN identities ON identities.id = $1 AND identities.deleted_at IS NULL
WHERE letters.id = $2
  AND letters.recipient_id = $1
  AND letters.opened_at IS NOT NULL
  AND letters.recipient_removed_at IS NULL
`

type GetLetterForRecipientParams struct {
	RecipientID int64
	ID          string
}

func (q *Queries) GetLetterForRecipient(ctx context.Context, arg GetLetterForRecipientParams) (Letter, error) {
	row := q.db.QueryRow(ctx, getLetterForRecipient, arg.RecipientID, arg.ID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const getLetterForSender = `-- name: GetLetterForSender :one
SELECT letters.id, letters.sender_id, letters.recipient_id, letters.sender_alias, letters.recipient_alias, letters.body_ciphertext, letters.body_nonce, letters.body_wrapped_key, letters.body_kms_key_id, letters.body_encryption_version, letters.fold_seed, letters.created_at, letters.claimed_at, letters.claim_expires_at, letters.opened_at, letters.reply_id, letters.reply_ciphertext, letters.reply_nonce, letters.reply_wrapped_key, letters.reply_kms_key_id, letters.reply_encryption_version, letters.replied_at, letters.withdrawn_at, letters.expires_at, letters.sender_removed_at, letters.recipient_removed_at FROM letters
JOIN identities ON identities.id = $1 AND identities.deleted_at IS NULL
WHERE letters.id = $2
  AND letters.sender_id = $1
  AND letters.sender_removed_at IS NULL
`

type GetLetterForSenderParams struct {
	SenderID int64
	ID       string
}

func (q *Queries) GetLetterForSender(ctx context.Context, arg GetLetterForSenderParams) (Letter, error) {
	row := q.db.QueryRow(ctx, getLetterForSender, arg.SenderID, arg.ID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const lockLetterForRecipient = `-- name: LockLetterForRecipient :one
SELECT id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at FROM letters
WHERE id = $1 AND recipient_id = $2
FOR UPDATE
`

type LockLetterForRecipientParams struct {
	ID          string
	RecipientID pgtype.Int8
}

func (q *Queries) LockLetterForRecipient(ctx context.Context, arg LockLetterForRecipientParams) (Letter, error) {
	row := q.db.QueryRow(ctx, lockLetterForRecipient, arg.ID, arg.RecipientID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const lockLetterForSender = `-- name: LockLetterForSender :one
SELECT id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at FROM letters
WHERE id = $1 AND sender_id = $2
FOR UPDATE
`

type LockLetterForSenderParams struct {
	ID       string
	SenderID int64
}

func (q *Queries) LockLetterForSender(ctx context.Context, arg LockLetterForSenderParams) (Letter, error) {
	row := q.db.QueryRow(ctx, lockLetterForSender, arg.ID, arg.SenderID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const openLetter = `-- name: OpenLetter :one
UPDATE letters
SET opened_at = now(), claim_expires_at = NULL
WHERE letters.id = $1
  AND letters.recipient_id = $2
  AND letters.opened_at IS NULL
  AND letters.claim_expires_at > now()
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $2 AND deleted_at IS NULL)
RETURNING id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at
`

type OpenLetterParams struct {
	ID          string
	RecipientID pgtype.Int8
}

func (q *Queries) OpenLetter(ctx context.Context, arg OpenLetterParams) (Letter, error) {
	row := q.db.QueryRow(ctx, openLetter, arg.ID, arg.RecipientID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}

const withdrawLetter = `-- name: WithdrawLetter :one
UPDATE letters
SET withdrawn_at = now()
WHERE letters.id = $1
  AND letters.sender_id = $2
  AND letters.recipient_id IS NULL
  AND letters.withdrawn_at IS NULL
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $2 AND deleted_at IS NULL)
RETURNING id, sender_id, recipient_id, sender_alias, recipient_alias, body_ciphertext, body_nonce, body_wrapped_key, body_kms_key_id, body_encryption_version, fold_seed, created_at, claimed_at, claim_expires_at, opened_at, reply_id, reply_ciphertext, reply_nonce, reply_wrapped_key, reply_kms_key_id, reply_encryption_version, replied_at, withdrawn_at, expires_at, sender_removed_at, recipient_removed_at
`

type WithdrawLetterParams struct {
	ID       string
	SenderID int64
}

func (q *Queries) WithdrawLetter(ctx context.Context, arg WithdrawLetterParams) (Letter, error) {
	row := q.db.QueryRow(ctx, withdrawLetter, arg.ID, arg.SenderID)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.SenderAlias,
		&i.RecipientAlias,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.BodyWrappedKey,
		&i.BodyKmsKeyID,
		&i.BodyEncryptionVersion,
		&i.FoldSeed,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.OpenedAt,
		&i.ReplyID,
		&i.ReplyCiphertext,
		&i.ReplyNonce,
		&i.ReplyWrappedKey,
		&i.ReplyKmsKeyID,
		&i.ReplyEncryptionVersion,
		&i.RepliedAt,
		&i.WithdrawnAt,
		&i.ExpiresAt,
		&i.SenderRemovedAt,
		&i.RecipientRemovedAt,
	)
	return i, err
}
