// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limits.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRateLimitEvents = `-- name: CountRateLimitEvents :one
SELECT count(*) FROM rate_limit_events
WHERE identity_id = $1
  AND kind = $2
  AND created_at >= $3
`

type CountRateLimitEventsParams struct {
	IdentityID int64
	Kind       int16
	Since      pgtype.Timestamptz
}

func (q *Queries) CountRateLimitEvents(ctx context.Context, arg CountRateLimitEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRateLimitEvents, arg.IdentityID, arg.Kind, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldRateLimitEvents = `-- name: DeleteOldRateLimitEvents :execrows
DELETE FROM rate_limit_events
WHERE created_at < $1
`

func (q *Queries) DeleteOldRateLimitEvents(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRateLimitEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldRateLimitEventsBatch = `-- name: DeleteOldRateLimitEventsBatch :many
WITH expired AS (
    SELECT id FROM rate_limit_events
    WHERE created_at < now() - make_interval(secs => $1::integer)
    ORDER BY created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
DELETE FROM rate_limit_events
USING expired
WHERE rate_limit_events.id = expired.id
RETURNING rate_limit_events.id
`

type DeleteOldRateLimitEventsBatchParams struct {
	RetentionSeconds int32
	BatchSize        int32
}

func (q *Queries) DeleteOldRateLimitEventsBatch(ctx context.Context, arg DeleteOldRateLimitEventsBatchParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteOldRateLimitEventsBatch, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateLimitAllowed = `-- name: RateLimitAllowed :one
SELECT
    ($1::integer <= 0 OR NOT EXISTS (
        SELECT 1 FROM rate_limit_events
        WHERE rate_limit_events.identity_id = $2
          AND rate_limit_events.kind = $3
          AND rate_limit_events.created_at >= now() - make_interval(secs => $1::integer)
    ))
    AND ($4::integer <= 0 OR (
        SELECT count(*) FROM rate_limit_events
        WHERE rate_limit_events.identity_id = $2
          AND rate_limit_events.kind = $3
          AND rate_limit_events.created_at >= now() - interval '1 hour'
    ) < $4::integer)
    AND ($5::integer <= 0 OR (
        SELECT count(*) FROM rate_limit_events
        WHERE rate_limit_events.identity_id = $2
          AND rate_limit_events.kind = $3
          AND rate_limit_events.created_at >= now() - interval '1 day'
    ) < $5::integer) AS allowed
`

type RateLimitAllowedParams struct {
	CooldownSeconds int32
	RateIdentityID  int64
	RateKind        int16
	HourLimit       int32
	DayLimit        int32
}

func (q *Queries) RateLimitAllowed(ctx context.Context, arg RateLimitAllowedParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, rateLimitAllowed,
		arg.CooldownSeconds,
		arg.RateIdentityID,
		arg.RateKind,
		arg.HourLimit,
		arg.DayLimit,
	)
	var allowed pgtype.Bool
	err := row.Scan(&allowed)
	return allowed, err
}

const recordRateLimitEvent = `-- name: RecordRateLimitEvent :one
INSERT INTO rate_limit_events (identity_id, kind)
SELECT $1, $2
WHERE EXISTS (SELECT 1 FROM identities WHERE id = $1 AND deleted_at IS NULL)
RETURNING id, identity_id, kind, created_at
`

type RecordRateLimitEventParams struct {
	IdentityID int64
	Kind       int16
}

func (q *Queries) RecordRateLimitEvent(ctx context.Context, arg RecordRateLimitEventParams) (RateLimitEvent, error) {
	row := q.db.QueryRow(ctx, recordRateLimitEvent, arg.IdentityID, arg.Kind)
	var i RateLimitEvent
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}
