// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessSession struct {
	TokenHash     []byte
	IdentityID    int64
	KeyThumbprint []byte
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

type AliasReservation struct {
	AliasKey   string
	ReservedAt pgtype.Timestamptz
}

type AuthChallenge struct {
	ID            string
	IdentityID    pgtype.Int8
	PublicKey     []byte
	KeyThumbprint []byte
	Purpose       int16
	NonceHash     []byte
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	UsedAt        pgtype.Timestamptz
}

type Block struct {
	BlockerID int64
	BlockedID int64
	CreatedAt pgtype.Timestamptz
}

type DpopReplay struct {
	SessionTokenHash []byte
	JtiHash          []byte
	ExpiresAt        pgtype.Timestamptz
}

type Identity struct {
	ID             int64
	PublicKey      []byte
	KeyThumbprint  []byte
	RevocationHash []byte
	Alias          pgtype.Text
	AliasKey       pgtype.Text
	CreatedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Invite struct {
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RedeemedAt pgtype.Timestamptz
	RedeemedBy pgtype.Int8
	RevokedAt  pgtype.Timestamptz
}

type Letter struct {
	ID                     string
	SenderID               int64
	RecipientID            pgtype.Int8
	SenderAlias            string
	RecipientAlias         pgtype.Text
	BodyCiphertext         []byte
	BodyNonce              []byte
	BodyWrappedKey         []byte
	BodyKmsKeyID           string
	BodyEncryptionVersion  int16
	FoldSeed               int64
	CreatedAt              pgtype.Timestamptz
	ClaimedAt              pgtype.Timestamptz
	ClaimExpiresAt         pgtype.Timestamptz
	OpenedAt               pgtype.Timestamptz
	ReplyID                pgtype.Text
	ReplyCiphertext        []byte
	ReplyNonce             []byte
	ReplyWrappedKey        []byte
	ReplyKmsKeyID          pgtype.Text
	ReplyEncryptionVersion pgtype.Int2
	RepliedAt              pgtype.Timestamptz
	WithdrawnAt            pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	SenderRemovedAt        pgtype.Timestamptz
	RecipientRemovedAt     pgtype.Timestamptz
}

type ModerationAudit struct {
	ID               int64
	RequestID        string
	ReportID         string
	ModeratorSubject string
	Action           int16
	Purpose          string
	Outcome          int16
	CreatedAt        pgtype.Timestamptz
	PurgeAt          pgtype.Timestamptz
}

type RateLimitEvent struct {
	ID         int64
	IdentityID int64
	Kind       int16
	CreatedAt  pgtype.Timestamptz
}

type Report struct {
	ID                        string
	LetterID                  string
	ReporterID                int64
	ReportedIdentityID        int64
	Target                    int16
	Reason                    int16
	CreatedAt                 pgtype.Timestamptz
	ReviewedAt                pgtype.Timestamptz
	ReviewedBy                pgtype.Text
	Disposition               pgtype.Int2
	ClosedAt                  pgtype.Timestamptz
	EvidencePurgeAt           pgtype.Timestamptz
	RecordPurgeAt             pgtype.Timestamptz
	EvidenceCiphertext        []byte
	EvidenceNonce             []byte
	EvidenceWrappedKey        []byte
	EvidenceKmsKeyID          pgtype.Text
	EvidenceEncryptionVersion pgtype.Int2
	EvidencePurgedAt          pgtype.Timestamptz
}
