// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeReport = `-- name: CloseReport :one
UPDATE reports
SET disposition = COALESCE(disposition, $1),
    closed_at = COALESCE(closed_at, now()),
    evidence_purge_at = COALESCE(evidence_purge_at, now() + interval '90 days'),
    record_purge_at = COALESCE(record_purge_at, now() + interval '1 year')
WHERE id = $2
  AND reviewed_at IS NOT NULL
  AND (disposition IS NULL OR disposition = $1)
RETURNING id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at
`

type CloseReportParams struct {
	Disposition pgtype.Int2
	ID          string
}

func (q *Queries) CloseReport(ctx context.Context, arg CloseReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, closeReport, arg.Disposition, arg.ID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const createModerationAudit = `-- name: CreateModerationAudit :one
INSERT INTO moderation_audit (
    request_id, report_id, moderator_subject, action, purpose, outcome, purge_at
) VALUES (
    $1, $2, $3,
    $4, 'reported-content-review', $5, now() + interval '1 year'
)
RETURNING id, request_id, report_id, moderator_subject, action, purpose, outcome, created_at, purge_at
`

type CreateModerationAuditParams struct {
	RequestID        string
	ReportID         string
	ModeratorSubject string
	Action           int16
	Outcome          int16
}

func (q *Queries) CreateModerationAudit(ctx context.Context, arg CreateModerationAuditParams) (ModerationAudit, error) {
	row := q.db.QueryRow(ctx, createModerationAudit,
		arg.RequestID,
		arg.ReportID,
		arg.ModeratorSubject,
		arg.Action,
		arg.Outcome,
	)
	var i ModerationAudit
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ReportID,
		&i.ModeratorSubject,
		&i.Action,
		&i.Purpose,
		&i.Outcome,
		&i.CreatedAt,
		&i.PurgeAt,
	)
	return i, err
}

const getDisabledIdentityFromReport = `-- name: GetDisabledIdentityFromReport :one
SELECT reported_identity_id FROM reports
WHERE id = $1 AND disposition = 3 AND closed_at IS NOT NULL
`

func (q *Queries) GetDisabledIdentityFromReport(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getDisabledIdentityFromReport, id)
	var reported_identity_id int64
	err := row.Scan(&reported_identity_id)
	return reported_identity_id, err
}

const getModerationAuditByRequestID = `-- name: GetModerationAuditByRequestID :one
SELECT id, request_id, report_id, moderator_subject, action, purpose, outcome, created_at, purge_at FROM moderation_audit
WHERE request_id = $1
`

func (q *Queries) GetModerationAuditByRequestID(ctx context.Context, requestID string) (ModerationAudit, error) {
	row := q.db.QueryRow(ctx, getModerationAuditByRequestID, requestID)
	var i ModerationAudit
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ReportID,
		&i.ModeratorSubject,
		&i.Action,
		&i.Purpose,
		&i.Outcome,
		&i.CreatedAt,
		&i.PurgeAt,
	)
	return i, err
}

const getReviewableReportForOwner = `-- name: GetReviewableReportForOwner :one
SELECT id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at FROM reports
WHERE id = $1
  AND reviewed_by = $2
  AND evidence_purged_at IS NULL
  AND (evidence_purge_at IS NULL OR evidence_purge_at > clock_timestamp())
`

type GetReviewableReportForOwnerParams struct {
	ID               string
	ModeratorSubject pgtype.Text
}

func (q *Queries) GetReviewableReportForOwner(ctx context.Context, arg GetReviewableReportForOwnerParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReviewableReportForOwner, arg.ID, arg.ModeratorSubject)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const lockNextUnreviewedReport = `-- name: LockNextUnreviewedReport :one
SELECT id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at FROM reports
WHERE reviewed_at IS NULL
  AND evidence_purged_at IS NULL
  AND (evidence_purge_at IS NULL OR evidence_purge_at > clock_timestamp())
ORDER BY created_at, id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) LockNextUnreviewedReport(ctx context.Context) (Report, error) {
	row := q.db.QueryRow(ctx, lockNextUnreviewedReport)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const lockReportForClose = `-- name: LockReportForClose :one
SELECT id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at FROM reports
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockReportForClose(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, lockReportForClose, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const lockReportForReview = `-- name: LockReportForReview :one
SELECT id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at FROM reports
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockReportForReview(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, lockReportForReview, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const markReportReviewed = `-- name: MarkReportReviewed :one
UPDATE reports
SET reviewed_at = COALESCE(reviewed_at, now()),
    reviewed_by = COALESCE(reviewed_by, $1)
WHERE id = $2
  AND (reviewed_by IS NULL OR reviewed_by = $1)
  AND evidence_purged_at IS NULL
  AND (evidence_purge_at IS NULL OR evidence_purge_at > clock_timestamp())
RETURNING id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at
`

type MarkReportReviewedParams struct {
	ModeratorSubject pgtype.Text
	ID               string
}

func (q *Queries) MarkReportReviewed(ctx context.Context, arg MarkReportReviewedParams) (Report, error) {
	row := q.db.QueryRow(ctx, markReportReviewed, arg.ModeratorSubject, arg.ID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}
