// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replays.sql

package dbgen

import (
	"context"
)

const insertDPoPReplay = `-- name: InsertDPoPReplay :execrows
INSERT INTO dpop_replays (session_token_hash, jti_hash, expires_at)
SELECT access_sessions.token_hash, $1, access_sessions.expires_at
FROM access_sessions
JOIN identities ON identities.id = access_sessions.identity_id
WHERE access_sessions.token_hash = $2
  AND access_sessions.revoked_at IS NULL
  AND access_sessions.expires_at > now()
  AND identities.deleted_at IS NULL
  AND identities.key_thumbprint = access_sessions.key_thumbprint
`

type InsertDPoPReplayParams struct {
	JtiHash          []byte
	SessionTokenHash []byte
}

func (q *Queries) InsertDPoPReplay(ctx context.Context, arg InsertDPoPReplayParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDPoPReplay, arg.JtiHash, arg.SessionTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
