// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    id, letter_id, reporter_id, reported_identity_id, target, reason,
    evidence_ciphertext, evidence_nonce, evidence_wrapped_key,
    evidence_kms_key_id, evidence_encryption_version, created_at
)
SELECT $1,
       letters.id,
       $2,
       CASE $3::smallint WHEN 1 THEN letters.sender_id ELSE letters.recipient_id END,
       $3,
       $4,
       $5,
       $6,
       $7,
       $8,
       $9,
       clock_timestamp()
FROM letters
WHERE letters.id = $10
  AND letters.opened_at IS NOT NULL
  AND (
      ($3::smallint = 1 AND letters.recipient_id = $2 AND letters.recipient_removed_at IS NULL)
      OR ($3::smallint = 2 AND letters.sender_id = $2 AND letters.reply_id IS NOT NULL AND letters.sender_removed_at IS NULL)
  )
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $2 AND deleted_at IS NULL)
RETURNING reports.id, reports.letter_id, reports.reporter_id, reports.reported_identity_id, reports.target, reports.reason, reports.created_at, reports.reviewed_at, reports.reviewed_by, reports.disposition, reports.closed_at, reports.evidence_purge_at, reports.record_purge_at, reports.evidence_ciphertext, reports.evidence_nonce, reports.evidence_wrapped_key, reports.evidence_kms_key_id, reports.evidence_encryption_version, reports.evidence_purged_at
`

type CreateReportParams struct {
	ID                        string
	ReporterID                int64
	Target                    int16
	Reason                    int16
	EvidenceCiphertext        []byte
	EvidenceNonce             []byte
	EvidenceWrappedKey        []byte
	EvidenceKmsKeyID          pgtype.Text
	EvidenceEncryptionVersion pgtype.Int2
	LetterID                  string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReporterID,
		arg.Target,
		arg.Reason,
		arg.EvidenceCiphertext,
		arg.EvidenceNonce,
		arg.EvidenceWrappedKey,
		arg.EvidenceKmsKeyID,
		arg.EvidenceEncryptionVersion,
		arg.LetterID,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const getReportByIDForReporter = `-- name: GetReportByIDForReporter :one
SELECT id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at FROM reports
WHERE reports.id = $1
  AND reports.reporter_id = $2
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $2 AND deleted_at IS NULL)
`

type GetReportByIDForReporterParams struct {
	ID         string
	ReporterID int64
}

func (q *Queries) GetReportByIDForReporter(ctx context.Context, arg GetReportByIDForReporterParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByIDForReporter, arg.ID, arg.ReporterID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const getReportByLetterForReporter = `-- name: GetReportByLetterForReporter :one
SELECT id, letter_id, reporter_id, reported_identity_id, target, reason, created_at, reviewed_at, reviewed_by, disposition, closed_at, evidence_purge_at, record_purge_at, evidence_ciphertext, evidence_nonce, evidence_wrapped_key, evidence_kms_key_id, evidence_encryption_version, evidence_purged_at FROM reports
WHERE reports.letter_id = $1
  AND reports.reporter_id = $2
  AND EXISTS (SELECT 1 FROM identities WHERE identities.id = $2 AND deleted_at IS NULL)
`

type GetReportByLetterForReporterParams struct {
	LetterID   string
	ReporterID int64
}

func (q *Queries) GetReportByLetterForReporter(ctx context.Context, arg GetReportByLetterForReporterParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByLetterForReporter, arg.LetterID, arg.ReporterID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.LetterID,
		&i.ReporterID,
		&i.ReportedIdentityID,
		&i.Target,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Disposition,
		&i.ClosedAt,
		&i.EvidencePurgeAt,
		&i.RecordPurgeAt,
		&i.EvidenceCiphertext,
		&i.EvidenceNonce,
		&i.EvidenceWrappedKey,
		&i.EvidenceKmsKeyID,
		&i.EvidenceEncryptionVersion,
		&i.EvidencePurgedAt,
	)
	return i, err
}

const hideReportedLetter = `-- name: HideReportedLetter :execrows
UPDATE letters
SET recipient_removed_at = CASE WHEN reports.target = 1 THEN clock_timestamp() ELSE letters.recipient_removed_at END,
    sender_removed_at = CASE WHEN reports.target = 2 THEN clock_timestamp() ELSE letters.sender_removed_at END
FROM reports
WHERE reports.id = $1
  AND reports.letter_id = letters.id
  AND reports.reporter_id = $2
`

type HideReportedLetterParams struct {
	ReportID   string
	ReporterID int64
}

func (q *Queries) HideReportedLetter(ctx context.Context, arg HideReportedLetterParams) (int64, error) {
	result, err := q.db.Exec(ctx, hideReportedLetter, arg.ReportID, arg.ReporterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
