// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accessSessionExpired = `-- name: AccessSessionExpired :one
SELECT EXISTS (
    SELECT 1 FROM access_sessions
    WHERE token_hash = $1
      AND expires_at <= now()
      AND revoked_at IS NULL
) AS expired
`

func (q *Queries) AccessSessionExpired(ctx context.Context, tokenHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, accessSessionExpired, tokenHash)
	var expired bool
	err := row.Scan(&expired)
	return expired, err
}

const consumeAuthChallenge = `-- name: ConsumeAuthChallenge :one
UPDATE auth_challenges
SET used_at = clock_timestamp()
WHERE id = $1
  AND purpose = $2
  AND used_at IS NULL
  AND expires_at > clock_timestamp()
RETURNING id, identity_id, public_key, key_thumbprint, purpose, nonce_hash, created_at, expires_at, used_at
`

type ConsumeAuthChallengeParams struct {
	ID      string
	Purpose int16
}

func (q *Queries) ConsumeAuthChallenge(ctx context.Context, arg ConsumeAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, consumeAuthChallenge, arg.ID, arg.Purpose)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.Purpose,
		&i.NonceHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createAccessSession = `-- name: CreateAccessSession :one
INSERT INTO access_sessions (token_hash, identity_id, key_thumbprint, expires_at)
VALUES ($1, $2, $3, now() + interval '15 minutes')
RETURNING token_hash, identity_id, key_thumbprint, created_at, expires_at, revoked_at
`

type CreateAccessSessionParams struct {
	TokenHash     []byte
	IdentityID    int64
	KeyThumbprint []byte
}

func (q *Queries) CreateAccessSession(ctx context.Context, arg CreateAccessSessionParams) (AccessSession, error) {
	row := q.db.QueryRow(ctx, createAccessSession, arg.TokenHash, arg.IdentityID, arg.KeyThumbprint)
	var i AccessSession
	err := row.Scan(
		&i.TokenHash,
		&i.IdentityID,
		&i.KeyThumbprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAuthChallenge = `-- name: CreateAuthChallenge :one
INSERT INTO auth_challenges (
    id, identity_id, public_key, key_thumbprint, purpose, nonce_hash, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, now() + interval '5 minutes'
)
RETURNING id, identity_id, public_key, key_thumbprint, purpose, nonce_hash, created_at, expires_at, used_at
`

type CreateAuthChallengeParams struct {
	ID            string
	IdentityID    pgtype.Int8
	PublicKey     []byte
	KeyThumbprint []byte
	Purpose       int16
	NonceHash     []byte
}

func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, createAuthChallenge,
		arg.ID,
		arg.IdentityID,
		arg.PublicKey,
		arg.KeyThumbprint,
		arg.Purpose,
		arg.NonceHash,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.Purpose,
		&i.NonceHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getActiveAccessSession = `-- name: GetActiveAccessSession :one
SELECT access_sessions.token_hash, access_sessions.identity_id, access_sessions.key_thumbprint, access_sessions.created_at, access_sessions.expires_at, access_sessions.revoked_at
FROM access_sessions
JOIN identities ON identities.id = access_sessions.identity_id
WHERE access_sessions.token_hash = $1
  AND access_sessions.revoked_at IS NULL
  AND access_sessions.expires_at > now()
  AND identities.deleted_at IS NULL
  AND identities.key_thumbprint = access_sessions.key_thumbprint
`

func (q *Queries) GetActiveAccessSession(ctx context.Context, tokenHash []byte) (AccessSession, error) {
	row := q.db.QueryRow(ctx, getActiveAccessSession, tokenHash)
	var i AccessSession
	err := row.Scan(
		&i.TokenHash,
		&i.IdentityID,
		&i.KeyThumbprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthChallengeForUpdate = `-- name: GetAuthChallengeForUpdate :one
SELECT id, identity_id, public_key, key_thumbprint, purpose, nonce_hash, created_at, expires_at, used_at FROM auth_challenges
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAuthChallengeForUpdate(ctx context.Context, id string) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, getAuthChallengeForUpdate, id)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.PublicKey,
		&i.KeyThumbprint,
		&i.Purpose,
		&i.NonceHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const revokeIdentitySessions = `-- name: RevokeIdentitySessions :execrows
UPDATE access_sessions
SET revoked_at = now()
WHERE identity_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeIdentitySessions(ctx context.Context, identityID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeIdentitySessions, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
